import type { CollectionConfig } from 'payload'
import { authenticated } from '../../access/authenticated'

export const Cars: CollectionConfig = {
  slug: 'cars',
  admin: {
    useAsTitle: 'model',
    defaultColumns: ['model', 'packageName', 'normalPrice', 'holidayPrice'],
  },
  access: {
    admin: authenticated,
    create: authenticated,
    delete: authenticated,
    read: authenticated,
    update: authenticated,
  },
  fields: [
    {
      name: 'model',
      type: 'text',
      required: true,
      label: 'Model',
    },
    {
      name: 'packageName',
      type: 'text',
      label: 'Package Name',
    },
    {
      name: 'packageDescription',
      type: 'text',
      label: 'Package Description',
    },
    {
      name: 'normalPrice',
      type: 'number',
      required: true,
      label: 'Normal Rental Price per Day',
      min: 0,
    },
    {
      name: 'holidayPrice',
      type: 'number',
      required: true,
      label: 'Holiday Rental Price per Day',
      min: 0,
    },
    {
      name: 'minRentalPeriod',
      type: 'number',
      required: true,
      label: 'Minimum Rental Period',
      min: 0,
    },
    {
      name: 'normalPriceMinRentalPeriod',
      type: 'number',
      required: true,
      label: 'Normal Rental Price per Day for Minimum Rental Period',
      min: 0,
    },
    {
      name: 'holidayPriceMinRentalPeriod',
      type: 'number',
      required: true,
      label: 'Holiday Rental Price per Day for Minimum Rental Period',
      min: 0,
    },
    {
      name: 'insuranceFee',
      type: 'number',
      required: true,
      label: 'Insurance Fee per Day',
      min: 0,
    },
    {
      name: 'cleaningFee',
      type: 'number',
      required: true,
      label: 'Cleaning Fee per Day',
      min: 0,
    },
    {
      name: 'mileage',
      type: 'number',
      required: true,
      label: 'Mileage per Day',
      min: 0,
    },
    {
      name: 'campingTable',
      type: 'checkbox',
      required: true,
      label: 'Camping Table',
    },
    {
      name: 'campingChair',
      type: 'checkbox',
      required: true,
      label: 'Camping Chair',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: '',
      type: 'checkbox',
      required: true,
      label: '',
    },
    {
      name: 'image',
      type: 'upload',
      relationTo: 'media',
      label: 'Image',
    },
    {
      name: 'available',
      type: 'checkbox',
      required: true,
      label: 'Available',
    },
  ],
}
