import type { CollectionConfig } from 'payload'
import { authenticated } from '../../access/authenticated'

export const Cars: CollectionConfig = {
  slug: 'cars',
  admin: {
    useAsTitle: 'model',
    defaultColumns: ['brand', 'model', 'packageName', 'normalPrice', 'holidayPrice', 'status'],
  },
  access: {
    admin: authenticated,
    create: authenticated,
    delete: authenticated,
    read: authenticated,
    update: authenticated,
  },
  fields: [
    {
      name: 'brand',
      type: 'select',
      required: true,
      label: 'Brand',
      options: [
        { label: 'Sunlight', value: 'sunlight' },
        { label: 'Mercedes-Benz', value: 'mercedes-benz' },
        { label: 'Ford', value: 'ford' },
      ],
    },
    {
      name: 'model',
      type: 'text',
      required: true,
      label: 'Model',
    },
    {
      name: 'packageName',
      type: 'text',
      label: 'Package Name',
    },
    {
      name: 'packageDescription',
      type: 'text',
      label: 'Package Description',
    },
    {
      name: 'normalPrice',
      type: 'number',
      required: true,
      label: 'Normal Rental Price per Day',
      min: 0,
    },
    {
      name: 'holidayPrice',
      type: 'number',
      required: true,
      label: 'Holiday Rental Price per Day',
      min: 0,
    },
    {
      name: 'minRentalPeriod',
      type: 'number',
      required: true,
      label: 'Minimum Rental Period (Days)',
      min: 0,
    },
    {
      name: 'normalPriceMinRentalPeriod',
      type: 'number',
      required: true,
      label: 'Normal Rental Price per Day for Minimum Rental Period',
      min: 0,
    },
    {
      name: 'holidayPriceMinRentalPeriod',
      type: 'number',
      required: true,
      label: 'Holiday Rental Price per Day for Minimum Rental Period',
      min: 0,
    },
    {
      name: 'insuranceFee',
      type: 'number',
      required: true,
      label: 'Insurance Fee per Day',
      min: 0,
    },
    {
      name: 'cleaningFee',
      type: 'number',
      required: true,
      label: 'Cleaning Fee per Day',
      min: 0,
    },
    {
      name: 'mileage',
      type: 'number',
      required: true,
      label: 'Mileage per Day',
      min: 0,
    },
    {
      name: 'campingTable',
      type: 'checkbox',
      required: true,
      label: 'Camping Table',
    },
    {
      name: 'campingChair',
      type: 'checkbox',
      required: true,
      label: 'Camping Chair',
    },
    {
      name: 'mattress',
      type: 'checkbox',
      required: true,
      label: 'Mattress',
    },
    {
      name: 'gasStove',
      type: 'checkbox',
      required: true,
      label: 'Gas Stove',
    },
    {
      name: 'refrigerator',
      type: 'checkbox',
      required: true,
      label: 'Refrigerator',
    },
    {
      name: 'sink',
      type: 'checkbox',
      required: true,
      label: 'Sink',
    },
    {
      name: 'hvac',
      type: 'checkbox',
      required: true,
      label: 'HVAC',
    },
    {
      name: 'bathroom',
      type: 'checkbox',
      required: true,
      label: 'Bathroom',
    },
    {
      name: 'gasBarrel',
      type: 'checkbox',
      required: true,
      label: 'Gas Barrel',
    },
    {
      name: 'aroundViewMonitor',
      type: 'checkbox',
      required: true,
      label: 'Around View Monitor',
    },
    {
      name: 'status',
      label: 'Status',
      type: 'select',
      required: true,
      options: [
        { label: 'Available', value: 'available' },
        { label: 'Maintenance', value: 'maintenance' },
        { label: 'Reserved', value: 'reserved' },
      ],
      defaultValue: 'available',
    },
    {
      name: 'images',
      label: 'Images',
      type: 'array',
      minRows: 1,
      required: true,
      fields: [
        {
          name: 'image',
          label: 'Image',
          type: 'upload',
          relationTo: 'media',
          required: true,
        },
      ],
    },
  ],
}
